# Generated by Django 6.0.3 on 2026-04-14 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coverage', models.IntegerField()),
                ('deductible', models.IntegerField()),
                ('benefits', models.JSONField(default=list)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quote.insurer')),
                ('quote_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='Quote.quoterequest')),
            ],
        ),
    ]
