# Generated by Django 6.0.3 on 2026-04-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='premium',
            field=models.IntegerField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
