# Generated by Django 6.0.3 on 2026-04-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quote', '0003_insurer_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
