# Generated by Django 5.2.12 on 2026-04-06 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('is_uae_resident', models.BooleanField(default=False)),
                ('visa_status', models.CharField(blank=True, max_length=50, null=True)),
                ('emirates_of_visa', models.CharField(blank=True, max_length=50, null=True)),
                ('salary_scale', models.CharField(blank=True, max_length=50, null=True)),
                ('available_to_everyone', models.BooleanField(default=True)),
                ('source_form', models.CharField(blank=True, max_length=100, null=True)),
                ('need_car_insurance', models.BooleanField(default=False)),
                ('car_year', models.IntegerField(blank=True, null=True)),
                ('car_model', models.CharField(blank=True, max_length=100, null=True)),
                ('car_plate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('current_stage', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('source', models.CharField(choices=[('WEBSITE', 'Website'), ('REFERRAL', 'Referral'), ('DIRECT', 'Direct'), ('AD', 'Ad')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
