# Generated by Django 6.0.3 on 2026-04-22 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('product_type', models.CharField(blank=True, choices=[('general', 'General'), ('motor', 'Motor'), ('health', 'Health')], max_length=100, null=True)),
                ('delivery_channel', models.CharField(blank=True, choices=[('agent', 'Agent'), ('direct', 'Direct')], max_length=255, null=True, verbose_name='Lead Source')),
                ('insurance_type', models.CharField(blank=True, choices=[('car_insurance_new', 'Car Insurance New'), ('car_insance_renewal', 'Car Insurance Renewal'), ('fleet_new', 'Fleet New'), ('fleet_renewal', 'Fleet Renewal')], max_length=255, null=True, verbose_name='Insurance_type')),
                ('is_pep', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=False, max_length=100, verbose_name='PEP Status')),
                ('stage', models.CharField(choices=[('new_lead', 'New Lead'), ('assigned', 'Assigned'), ('non_contactable_1', 'Non Contactable 1'), ('non_contactable_2', 'Non Contactable 2'), ('non_contactable_3', 'Non Contactable 3'), ('contactable', 'Contactable'), ('requirement_gathering', 'Requirement Gathering'), ('sales_qualified_lead', 'Sales Qualified Lead')], default='Assigned', help_text='Current pipeline stage', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('QUALIFIED', 'Qualified'), ('LOST', 'Lost')], default='NEW', max_length=20)),
                ('is_favorite', models.BooleanField(default=False)),
                ('progress_score', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source', models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Call')], max_length=255, null=True, verbose_name='Lead Source')),
                ('sub_type', models.CharField(blank=True, choices=[('comprehensive_agency', 'Comprehensive - Agency'), ('comprehensive_non_agency', 'Comprehensive - Non Agency'), ('third_party', 'Third Party')], max_length=255, null=True, verbose_name='subtype')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_icon', models.URLField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
            ],
        ),
    ]
