# Generated by Django 4.2 on 2026-04-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_delivery_channel_alter_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='delivery_channel',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Call')], max_length=255, null=True, verbose_name='Preferred Contact Method'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('lead_source', 'Lead Source'), ('website', 'Website'), ('referral', 'Referral'), ('agent', 'Agent'), ('direct', 'Direct')], max_length=255, null=True, verbose_name='Lead Source'),
        ),
    ]
