# Generated by Django 6.0.3 on 2026-04-06 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user_icon", models.URLField(blank=True, null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="leads.lead"
                    ),
                ),
            ],
        ),
    ]
