# Generated by Django 6.0.3 on 2026-04-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_delivery_channel_alter_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('lead_source', 'Lead Source'), ('website', 'Website'), ('referral', 'Referral'), ('agent', 'Agent'), ('direct', 'Direct')], max_length=255, null=True, verbose_name='Lead Source'),
        ),
    ]
