# Generated by Django 6.0.3 on 2026-04-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_leadactivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="is_favorite",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="progress_score",
            field=models.IntegerField(default=0),
        ),
    ]
