# Generated by Django 6.0.3 on 2026-04-24 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deal_table'),
        ('leads', '0005_alter_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='product',
            field=models.OneToOneField(blank=True, db_column='product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_product', to='deals.deal'),
        ),
    ]
