# Generated by Django 3.2.25 on 2026-04-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_delete_deals'),
        ('leads', '0005_lead_is_favorite_lead_progress_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadactivity',
            name='lead',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.DeleteModel(
            name='LeadActivity',
        ),
    ]
