# Generated by GPT-5 on 2026-04-24

from django.db import migrations


def forwards(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    Deal = apps.get_model("deals", "Deal")

    # Backfill Lead.product_id from the existing Deal.lead FK.
    # If multiple deals exist for one lead, pick the most recently updated one.
    deals = (
        Deal.objects.exclude(lead_id__isnull=True)
        .order_by("lead_id", "-updated_at", "-id")
        .values_list("lead_id", "id")
    )

    chosen = {}
    for lead_id, deal_id in deals:
        if lead_id not in chosen:
            chosen[lead_id] = deal_id

    for lead_id, deal_id in chosen.items():
        Lead.objects.filter(id=lead_id, product_id__isnull=True).update(product_id=deal_id)


def backwards(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    Lead.objects.update(product_id=None)


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0006_lead_product"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

