# Generated by Django 6.0 on 2026-04-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_leadcomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeadComments',
            new_name='Note',
        ),
    ]
