# Generated by Django 6.0.3 on 2026-04-24 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_backfill_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'general_details',
            },
        ),
        migrations.CreateModel(
            name='MedicalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medical_details',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='general_product',
            field=models.OneToOneField(blank=True, db_column='general_product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='leads.generaldetails'),
        ),
        migrations.AddField(
            model_name='lead',
            name='medical_product',
            field=models.OneToOneField(blank=True, db_column='medical_product_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead', to='leads.medicaldetails'),
        ),
    ]
