# Generated by Django 3.2.25 on 2026-04-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_leadactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
    ]
