# Generated by GPT-5 on 2026-04-24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0008_generaldetails_medicaldetails_lead_general_product_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameField(
                    model_name="lead",
                    old_name="product",
                    new_name="motor_product",
                ),
                migrations.AlterField(
                    model_name="lead",
                    name="motor_product",
                    field=models.ForeignKey(
                        blank=True,
                        db_column="motor_product_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="motor_leads",
                        to="deals.deal",
                    ),
                ),
            ],
        )
    ]

