# Generated by Django 6.0 on 2026-04-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='leads.lead'),
            preserve_default=False,
        ),
    ]
