# Generated by Django 6.0.3 on 2026-04-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_rename_product_id_to_motor_product_id'),
        ('leads', '0011_move_insurance_and_subtype_to_motor_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='insurance_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sub_type',
        ),
    ]
