# Generated by Django 4.2 on 2026-04-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_auto_20260416_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={},
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='delivery_channel',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('broker', 'Broker')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_pep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('assigned', 'Assigned'), ('non_contactable_1', 'Non Contactable 1'), ('non_contactable_2', 'Non Contactable 2'), ('non_contactable_3', 'Non Contactable 3'), ('contactable', 'Contactable'), ('requirement_gathering', 'Requirement Gathering'), ('sales_qualified_lead', 'Sales Qualified Lead')], default='assigned', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
