# Generated by Django 6.0 on 2026-04-07 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_task_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_health_insurance', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('currently_insured', models.BooleanField(blank=True, null=True)),
                ('salary_band', models.CharField(blank=True, max_length=50, null=True)),
                ('emirates_id', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_hospitals_clinics', models.TextField(blank=True, null=True)),
                ('specific_benefits', models.TextField(blank=True, null=True)),
                ('basic_plan_type', models.CharField(blank=True, max_length=50, null=True)),
                ('co_payment', models.CharField(blank=True, max_length=50, null=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_info', to='leads.lead')),
            ],
        ),
    ]
