# Generated by GPT-5 on 2026-04-24

from django.db import migrations


def forwards(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    Deal = apps.get_model("deals", "Deal")

    # Move data from leads_lead.(insurance_type, sub_type) -> motor_details
    # using the existing FK relation motor_details.lead_id.
    for lead in Lead.objects.all().only("id", "insurance_type", "sub_type"):
        if not lead.insurance_type and not lead.sub_type:
            continue
        Deal.objects.filter(lead_id=lead.id).update(
            insurance_type=lead.insurance_type,
            sub_type=lead.sub_type,
        )


def backwards(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    Deal = apps.get_model("deals", "Deal")

    # Move data back (best-effort): take from motor_details rows.
    for lead in Lead.objects.all().only("id"):
        motor = (
            Deal.objects.filter(lead_id=lead.id)
            .order_by("-updated_at", "-id")
            .first()
        )
        if not motor:
            continue
        Lead.objects.filter(id=lead.id).update(
            insurance_type=motor.insurance_type,
            sub_type=motor.sub_type,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0004_deal_insurance_type_deal_sub_type"),
        ("leads", "0009_rename_product_id_to_motor_product_id"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

