# Generated by Django 6.0.3 on 2026-04-24

from django.db import migrations


def rename_product_column(apps, schema_editor):
    table_name = "leads_lead"
    existing_columns = {
        column.name for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), table_name
        )
    }

    if "product_id" in existing_columns and "motor_product_id" not in existing_columns:
        schema_editor.execute(
            f'ALTER TABLE "{table_name}" RENAME COLUMN "product_id" TO "motor_product_id"'
        )


def reverse_rename_product_column(apps, schema_editor):
    table_name = "leads_lead"
    existing_columns = {
        column.name for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(), table_name
        )
    }

    if "motor_product_id" in existing_columns and "product_id" not in existing_columns:
        schema_editor.execute(
            f'ALTER TABLE "{table_name}" RENAME COLUMN "motor_product_id" TO "product_id"'
        )


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0010_remove_lead_insurance_type_remove_lead_sub_type"),
    ]

    operations = [
        migrations.RunPython(rename_product_column, reverse_rename_product_column),
    ]
