# Generated by Django 6.0 on 2026-04-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_insuranceinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsuranceInfo',
            new_name='Insurance',
        ),
    ]
