# Generated by Django 6.0 on 2026-04-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_rename_insuranceinfo_insurance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Insurance',
            new_name='InsuranceInfo',
        ),
    ]
