# Generated by Django 6.0 on 2026-04-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_rename_insurance_insuranceinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceInfo',
        ),
    ]
