# Generated by Django 6.0.3 on 2026-04-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
    ]
