# Generated by Django 6.0.3 on 2026-04-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_rename_first_name_lead_name_remove_lead_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
