# Generated by Django 6.0.3 on 2026-04-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='delivery_channel',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('broker', 'Broker')], max_length=255, null=True, verbose_name='Lead Source'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_pep',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=False, verbose_name='PEP Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='product_type',
            field=models.CharField(blank=True, choices=[('life', 'Life'), ('health', 'Health'), ('motor', 'Motor'), ('travel', 'Travel'), ('property', 'Property')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('assigned', 'Assigned'), ('non_contactable_1', 'Non Contactable 1'), ('non_contactable_2', 'Non Contactable 2'), ('non_contactable_3', 'Non Contactable 3'), ('contactable', 'Contactable'), ('requirement_gathering', 'Requirement Gathering'), ('sales_qualified_lead', 'Sales Qualified Lead')], default='Assigned', help_text='Current pipeline stage', max_length=100),
        ),
    ]
