# Generated by Django 6.0.3 on 2026-04-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_lead_delivery_channel_alter_lead_is_pep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='insurance_type',
            field=models.CharField(blank=True, choices=[('car_insurance_new', 'Car Insurance New'), ('car_insance_renewal', 'Car Insurance Renewal'), ('fleet_new', 'Fleet New'), ('fleet_renewal', 'Fleet Renewal')], max_length=255, null=True, verbose_name='Insurance_type'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Call')], max_length=255, null=True, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('comprehensive_agency', 'Comprehensive - Agency'), ('comprehensive_non_agency', 'Comprehensive - Non Agency'), ('third_party', 'Third Party')], max_length=255, null=True, verbose_name='subtype'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='delivery_channel',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('direct', 'Direct')], max_length=255, null=True, verbose_name='Lead Source'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='product_type',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('motor', 'Motor'), ('health', 'Health')], max_length=100, null=True),
        ),
    ]
