# Generated by Django 6.0.3 on 2026-04-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_alter_insuranceinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
