# Generated by Django 4.2 on 2026-04-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_alter_insuranceinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
