# Generated by Django 6.0.3 on 2026-04-27 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_merge_20260424_1742'),
        ('insurance', '0011_provider_quote_indexes'),
        ('leads', '0012_fix_motor_product_column_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteresult',
            name='coverage_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='is_best_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='is_cheapest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='normalized_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='provider_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='quoteresult',
            name='plan_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quoteresult',
            name='premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quoteresult',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='quoteresult',
            name='vat',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='QuoteBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, max_length=32, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('best_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('partial_success', 'Partial Success'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('cache_expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('best_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='best_quote_batches', to='insurance.insuranceprovider')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_batches', to='deals.deal')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_batches', to='leads.lead')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_quote_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='quoterequestlog',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='insurance.quotebatch'),
        ),
        migrations.AddField(
            model_name='quoteresult',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='insurance.quotebatch'),
        ),
        migrations.AddIndex(
            model_name='quotebatch',
            index=models.Index(fields=['deal', '-requested_at'], name='qbatch_deal_req_idx'),
        ),
        migrations.AddIndex(
            model_name='quotebatch',
            index=models.Index(fields=['status', 'cache_expires_at'], name='qbatch_status_cache_idx'),
        ),
    ]
