# Generated by Django 6.0.3 on 2026-05-10 06:39

from django.db import migrations, models


def forwards_clear_legacy_active(apps, schema_editor):
    PolicyIssuance = apps.get_model("insurance", "PolicyIssuance")
    PolicyIssuance.objects.filter(issuance_status="active").update(
        issuance_status="payment_link_requested",
    )


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0015_policy_issuance'),
    ]

    operations = [
        migrations.RunPython(forwards_clear_legacy_active, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='policyissuance',
            name='issuance_status',
            field=models.CharField(choices=[('payment_link_requested', 'Payment link requested'), ('payment_link_received', 'Payment link received'), ('issued', 'Issued')], default='payment_link_requested', max_length=40),
        ),
    ]
