# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance", "0016_issuance_status_trim_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policyissuance",
            name="issuance_status",
            field=models.CharField(
                choices=[
                    ("payment_link_requested", "Payment link requested"),
                    ("payment_link_received", "Payment link received"),
                    ("issued", "Issued"),
                    ("active", "Active"),
                ],
                default="payment_link_requested",
                max_length=40,
            ),
        ),
    ]
