# Generated by Django 6.0.3 on 2026-05-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0017_policyissuance_issuance_status_active_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyissuance',
            name='issuance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_link_requested', 'Payment link requested'), ('payment_link_received', 'Payment link received'), ('issued', 'Issued'), ('active', 'Active')], default='pending', max_length=40),
        ),
    ]
