# Generated by Django 4.2 on 2026-05-21 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_alter_deal_insurance_type'),
        ('insurance', '0017_alter_insuranceinfo_id_alter_insuranceprovider_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyIssuance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_email', models.CharField(blank=True, max_length=254)),
                ('product_type', models.CharField(blank=True, max_length=255)),
                ('provider_code', models.CharField(blank=True, max_length=50)),
                ('provider_display_name', models.CharField(blank=True, max_length=255)),
                ('plan_name', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='AED', max_length=10)),
                ('base_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('addon_line_items', models.JSONField(blank=True, default=list)),
                ('dic_request_id', models.CharField(blank=True, max_length=64)),
                ('dic_scheme_payload', models.JSONField(blank=True, null=True)),
                ('choose_scheme_response', models.JSONField(blank=True, null=True)),
                ('quotation_no', models.CharField(blank=True, max_length=128)),
                ('payment_url', models.CharField(blank=True, max_length=2048)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('issuance_status', models.CharField(choices=[('pending', 'Pending'), ('payment_link_requested', 'Payment link requested'), ('payment_link_received', 'Payment link received'), ('issued', 'Issued'), ('active', 'Active')], default='pending', max_length=40)),
                ('checkout_submit_skipped', models.BooleanField(default=False)),
                ('choose_scheme_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_issuances', to='deals.deal')),
                ('quote_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_issuances', to='insurance.quotebatch')),
                ('quote_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_issuances', to='insurance.quoteresult')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='policyissuance',
            index=models.Index(fields=['deal', '-created_at'], name='pissue_deal_ctd_idx'),
        ),
        migrations.AddIndex(
            model_name='policyissuance',
            index=models.Index(fields=['-created_at'], name='pissue_ctd_idx'),
        ),
    ]
