# Generated by Django 6.0.3 on 2026-04-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealdocument',
            name='document_type',
            field=models.CharField(choices=[('driving_license_front', 'Driving License (Front)'), ('driving_license_back', 'Driving License (Back)'), ('emirates_id_front', 'Emirates ID (Front)'), ('emirates_id_back', 'Emirates ID (Back)'), ('mulkiya_id_front', 'Mulkiya ID (Front)'), ('mulkiya_id_back', 'Mulkiya ID (Back)'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
