# Generated by Django 3.2.25 on 2026-04-08 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_is_favorite_lead_progress_score'),
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='leads.lead'),
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
