# Generated by Django 6.0.3 on 2026-04-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_dealdocument_document_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deal',
            table='motor_details',
        ),
    ]
