# Generated by Django 3.2.25 on 2026-04-10 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20260408_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deals',
        ),
    ]
