# Generated by Django 4.2 on 2026-04-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_dealdocument_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealdocument',
            name='ocr_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='ocr_status',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
