# Generated by Django 6.0.3 on 2026-04-21 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_deal_dealdocument_delete_deals_delete_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dealdocument',
            name='deal',
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_id', models.IntegerField(choices=[(1, 'Potential Customer'), (2, 'Awaiting Additional Documents'), (3, 'Quotation'), (4, 'Follow up'), (5, 'High Value Leads'), (6, 'Hot/Responded'), (7, 'Documentation Request'), (8, 'Insurer Submission'), (9, 'Pending with Insurer'), (10, 'Payment Collection'), (11, 'Payment Pending'), (12, 'Payment Done'), (13, 'Policy Issuance'), (14, 'Billing'), (15, 'Lost Cases & Future Prospects')], default=1)),
                ('policy_type', models.CharField(choices=[('AUTO', 'Auto'), ('HOME', 'Home'), ('HEALTH', 'Health'), ('LIFE', 'Life'), ('BUSINESS', 'Business')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDERWRITING', 'Underwriting'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_policies', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_policies', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='deals.lead')),
            ],
        ),
        migrations.DeleteModel(
            name='Deal',
        ),
        migrations.DeleteModel(
            name='DealDocument',
        ),
    ]
