# Generated by Django 4.2 on 2026-04-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_dealdocument_ocr_response_dealdocument_ocr_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealdocument',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dealdocument',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
