# Generated by Django 6.0.3 on 2026-04-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deal_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='insurance_type',
            field=models.CharField(blank=True, choices=[('car_insurance_new', 'Car Insurance New'), ('car_insance_renewal', 'Car Insurance Renewal'), ('fleet_new', 'Fleet New'), ('fleet_renewal', 'Fleet Renewal')], max_length=255, null=True, verbose_name='Insurance_type'),
        ),
        migrations.AddField(
            model_name='deal',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('comprehensive_agency', 'Comprehensive - Agency'), ('comprehensive_non_agency', 'Comprehensive - Non Agency'), ('third_party', 'Third Party')], max_length=255, null=True, verbose_name='subtype'),
        ),
    ]
