# Generated by Django 3.2.25 on 2026-04-16 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_deal'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deal_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deals.deal')),
            ],
        ),
    ]
