# Generated by Django 6.0.3 on 2026-04-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_deal_insurance_type_deal_sub_type'),
        ('deals', '0004_dealdocument_score_dealdocument_source'),
    ]

    operations = [
    ]
