# Generated by Django 3.2.25 on 2026-04-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_dealdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='additional_field',
            field=models.TextField(blank=True, null=True),
        ),
    ]
