# Generated by Django 6.0.3 on 2026-04-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_merge_20260424_1539'),
        ('deals', '0005_merge_20260424_ocr_motor_branches'),
    ]

    operations = [
    ]
