# Generated by Django 4.2 on 2026-05-05 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_merge_20260424_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='sum_insured',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Market valuation (from Bayanaty) or manually entered sum insured for insurance providers', max_digits=12, null=True),
        ),
    ]
