# Generated by Django 4.2 on 2026-05-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_deal_sum_insured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='insurance_type',
            field=models.CharField(blank=True, choices=[('New Vehicle Registration', 'New Vehicle Registration'), ('Change Vehicle Ownership', 'Change Vehicle Ownership'), ('Vehicle Renewal', 'Vehicle Renewal'), ('Import Vehicle', 'Import Vehicle'), ('Export Certificate', 'Export Certificate'), ('Update Registration Information', 'Update Registration Information'), ('Issue Trade Plate', 'Issue Trade Plate'), ('Renewal Trade Plate', 'Renewal Trade Plate'), ('Vehicle Renewal with Change Number', 'Vehicle Renewal with Change Number')], max_length=255, null=True, verbose_name='Insurance_type'),
        ),
    ]
