# Generated by Django 5.2.6 on 2026-05-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deals", "0001_initial"),
        ("deals", "0008_alter_deal_insurance_type"),
    ]

    operations = []
