# Generated by Django 5.2.12 on 2026-04-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role_alter_customuser_id_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('general_manager', 'General manager'), ('operations_manager', 'Operations manager'), ('department_head', 'Department head'), ('underwriter', 'Underwriter'), ('sales_manager', 'Sales manager'), ('telecallers', 'Telecallers'), ('customers', 'Customers'), ('accounts', 'Accounts')], max_length=20, unique=True),
        ),
    ]
