# Generated by Django 6.0.3 on 2026-05-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_customuser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='modified_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
