# Generated by Django 6.0 on 2026-04-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], max_length=10)),
            ],
        ),
    ]
