# Generated by Django 6.0 on 2026-04-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrdocument',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='confidence_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='document_id',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='document_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='lead_id',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='product',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'Verified'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('LOW_CONFIDENCE', 'Low Confidence')], max_length=20),
        ),
    ]
