# Generated by Django 4.2 on 2026-04-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_ocrdocument_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrdocument',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
