# Generated by Django 6.0.3 on 2026-04-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_alter_ocrdocument_id'),
        ('documents', '0009_document'),
    ]

    operations = [
    ]
