# Generated by Django 6.0.3 on 2026-04-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_merge_0009_alter_ocrdocument_id_0009_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
