# Generated by Django 6.0.3 on 2026-04-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_ocrdocument_id'),
        ('documents', '0011_alter_ocrdocument_id'),
    ]

    operations = [
    ]
