# Generated by Django 6.0.3 on 2026-04-25 10:46

import mimetypes
import os
import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def forwards(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    DealDocument = apps.get_model("deals", "DealDocument")
    OCRDocument = apps.get_model("documents", "OCRDocument")

    for legacy in DealDocument.objects.all().iterator():
        file_name = legacy.file.name or ""
        guessed_type, _encoding = mimetypes.guess_type(file_name)
        Document.objects.create(
            name=os.path.basename(file_name),
            file=file_name,
            path=file_name,
            file_type=guessed_type or "application/octet-stream",
            document_type=legacy.document_type or "other",
            source=legacy.source,
            score=legacy.score,
            ocr_response=legacy.ocr_response,
            ocr_status=(
                "SUCCESS"
                if legacy.ocr_status is True
                else "FAILED" if legacy.ocr_status is False else "PENDING"
            ),
            status=(
                "VERIFIED"
                if legacy.status is True
                else "REJECTED" if legacy.status is False else "PENDING"
            ),
            motor_deal_id=legacy.deal_id,
            uploaded_at=legacy.uploaded_at,
        )

    for legacy in OCRDocument.objects.all().iterator():
        Document.objects.create(
            name=legacy.first_name,
            document_type=legacy.document_type or "other",
            score=legacy.confidence_score,
            status=legacy.status,
            source="ocr_legacy",
            uploaded_at=legacy.upload_date or timezone.now(),
        )


def backwards(apps, schema_editor):
    Document = apps.get_model("documents", "Document")
    Document.objects.filter(source__in=["ocr_legacy", "deal_form", "ocr_upload"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_merge_20260424_1742'),
        ('documents', '0012_merge_20260424_1742'),
        ('leads', '0012_fix_motor_product_column_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at', '-id']},
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='general_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.generaldetails'),
        ),
        migrations.AddField(
            model_name='document',
            name='medical_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.medicaldetails'),
        ),
        migrations.AddField(
            model_name='document',
            name='motor_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('LOW_CONFIDENCE', 'Low Confidence')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
