# Generated by Django 4.2 on 2026-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_document_reuploaded_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
