"""
Django settings for crm_pro project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from datetime import timedelta
from corsheaders.defaults import default_headers

DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024  
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024  

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def load_local_env(env_path):
    try:
        from dotenv import load_dotenv

        load_dotenv(env_path)
    except ModuleNotFoundError:
        pass

    if not env_path.exists():
        return

    for line in env_path.read_text().splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_local_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-k((b)6!9s(hu3ie@@k^b6l4$dc=bt%89kh*8e)r1$8hr^qmo+#"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False
DEBUG = True

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,10.230.10.4,20.233.10.43").split(",")

# CORS: cannot use CORS_ALLOW_ALL_ORIGINS=True with credentials (cookies).
_cors_default = (
    "http://localhost:5173,http://127.0.0.1:5173,"
    "http://10.230.10.4:5173,http://20.233.10.43:5173,"
    "http://localhost:5174,http://127.0.0.1:5174,"
    "http://localhost:3000,http://127.0.0.1:3000"
)
CORS_ALLOWED_ORIGINS = [
    o.strip()
    for o in os.environ.get("CORS_ALLOWED_ORIGINS", _cors_default).split(",")
    if o.strip()
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False
# Custom headers used by insurer proxies (e.g. DIC choose-scheme).
CORS_ALLOW_HEADERS = (
    *default_headers,
    "x-request-id",
)

CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get("CSRF_TRUSTED_ORIGINS", _cors_default).split(",")
    if o.strip()
]
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'api',
    'leads',
    'deals',
    'corsheaders',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    'Policys',
    'Task',
    'insurance',
    'documents.apps.DocumentsConfig',
    'apps.ocr.apps.OcrConfig',
    'apps.invoice.apps.InvoiceConfig',
    'Quote',
    'invoice',
    'email_integration'
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "crm_pro.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "crm_pro.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [ 'api.backends.EmailBackend',] 

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"




MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT = os.environ.get(
    "AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT",
    "",
)
AZURE_DOCUMENT_INTELLIGENCE_KEY = os.environ.get(
    "AZURE_DOCUMENT_INTELLIGENCE_KEY",
    "",
)
DOCUMENT_OCR_AUTO_PROCESS = os.environ.get("DOCUMENT_OCR_AUTO_PROCESS", "1").lower() in (
    "1",
    "true",
    "yes",
)
DOCUMENT_OCR_POLLING_TIMEOUT_SECONDS = int(
    os.environ.get("DOCUMENT_OCR_POLLING_TIMEOUT_SECONDS", "120")
)
DOCUMENT_OCR_LOW_CONFIDENCE_THRESHOLD = float(
    os.environ.get("DOCUMENT_OCR_LOW_CONFIDENCE_THRESHOLD", "0.70")
)

# Azure Form Recognizer (apps.ocr microservice)
AZURE_FORM_RECOGNIZER_ENDPOINT = os.environ.get(
    "AZURE_FORM_RECOGNIZER_ENDPOINT",
    os.environ.get("AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT", ""),
)
AZURE_FORM_RECOGNIZER_KEY = os.environ.get(
    "AZURE_FORM_RECOGNIZER_KEY",
    os.environ.get("AZURE_DOCUMENT_INTELLIGENCE_KEY", ""),
)
OCR_CONFIDENCE_THRESHOLD = float(
    os.environ.get("OCR_CONFIDENCE_THRESHOLD", "0.75")
)
OCR_POLLING_TIMEOUT_SECONDS = int(
    os.environ.get("OCR_POLLING_TIMEOUT_SECONDS", "120")
)
OCR_MAX_UPLOAD_BYTES = int(
    os.environ.get("OCR_MAX_UPLOAD_BYTES", str(10 * 1024 * 1024))
)

# Azure invoice extraction (apps.invoice microservice)
INVOICE_CONFIDENCE_THRESHOLD = float(
    os.environ.get("INVOICE_CONFIDENCE_THRESHOLD", "0.75")
)
INVOICE_POLLING_TIMEOUT_SECONDS = int(
    os.environ.get("INVOICE_POLLING_TIMEOUT_SECONDS", "120")
)
INVOICE_MAX_UPLOAD_BYTES = int(
    os.environ.get("INVOICE_MAX_UPLOAD_BYTES", str(10 * 1024 * 1024))
)



#FIXED REST_FRAMEWORK setting
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # moved here
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # sensible default
    ],
    'EXCEPTION_HANDLER': 'api.exception_handler.custom_exception_handler',
}

#Keep only ONE AUTHENTICATION_BACKENDS 
AUTHENTICATION_BACKENDS = [
    'api.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]



SIMPLE_JWT = {
    # Short-lived access token (Bearer in memory on the SPA).
    "ACCESS_TOKEN_LIFETIME": timedelta(
        minutes=int(os.environ.get("JWT_ACCESS_MINUTES", "15"))
    ),
    "REFRESH_TOKEN_LIFETIME": timedelta(
        days=int(os.environ.get("JWT_REFRESH_DAYS", "7"))
    ),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
}

# HttpOnly cookie for refresh token (must align with REFRESH_TOKEN_LIFETIME).
JWT_REFRESH_COOKIE_NAME = os.environ.get("JWT_REFRESH_COOKIE_NAME", "refresh_token")
JWT_REFRESH_COOKIE_PATH = "/"
JWT_COOKIE_SAMESITE = os.environ.get("JWT_COOKIE_SAMESITE", "Lax")
# Local HTTP dev: False. Production HTTPS: set True or DJANGO_DEBUG=0.
JWT_COOKIE_SECURE = os.environ.get("JWT_COOKIE_SECURE", "").lower() in (
    "1",
    "true",
    "yes",
) or (not DEBUG)
JWT_REFRESH_COOKIE_MAX_AGE = int(SIMPLE_JWT["REFRESH_TOKEN_LIFETIME"].total_seconds())
