# Generated by Django 5.2.6 on 2026-05-21 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("deals", "0001_initial"),
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="lead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deals",
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="dealdocument",
            name="deal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="deals.deal",
            ),
        ),
    ]
