# Generated by Django 6.0.3 on 2026-05-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('document_type', models.CharField(max_length=64)),
                ('target_schema', models.CharField(max_length=64)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_file', models.FileField(upload_to='invoice/uploads/%Y/%m/%d/')),
                ('model_used', models.CharField(blank=True, max_length=128)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('extracted_fields', models.JSONField(blank=True, null=True)),
                ('needs_review_fields', models.JSONField(blank=True, null=True)),
                ('confidence_scores', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='apps_invoi_status_8a1f2c_idx')],
            },
        ),
    ]
