# Generated by Django 4.2 on 2026-05-21 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoicejob',
            new_name='apps_invoic_status_e22a6d_idx',
            old_name='apps_invoi_status_8a1f2c_idx',
        ),
    ]
