# Generated by Django 6.0.4 on 2026-04-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('i_policy_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pol_no', models.IntegerField(blank=True, null=True)),
                ('on_poi_no', models.IntegerField(blank=True, null=True)),
                ('ion_poi_no', models.IntegerField(blank=True, null=True)),
                ('open_pol', models.BooleanField(default=False)),
                ('no_renewal', models.BooleanField(default=False)),
                ('partial_refund_del', models.BooleanField(default=False)),
                ('name_1a', models.CharField(blank=True, max_length=255, null=True)),
                ('address_1a', models.TextField(blank=True, null=True)),
                ('cover_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ins_name', models.CharField(blank=True, max_length=255, null=True)),
                ('ins_grp', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_grp', models.CharField(blank=True, max_length=100, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('exp_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('diff_date', models.DateTimeField(blank=True, null=True)),
                ('self_billing_date', models.DateTimeField(blank=True, null=True)),
                ('mode_of_payment', models.IntegerField(blank=True, null=True)),
                ('mode_of_payment_code', models.IntegerField(blank=True, null=True)),
                ('pay_inst_years', models.IntegerField(blank=True, null=True)),
                ('self_billing', models.CharField(blank=True, max_length=100, null=True)),
                ('self_billing_no', models.IntegerField(blank=True, null=True)),
                ('cti_amt', models.CharField(blank=True, max_length=100, null=True)),
                ('usr_name', models.CharField(blank=True, max_length=100, null=True)),
                ('t_remark', models.TextField(blank=True, null=True)),
                ('user_ref', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Policies',
                'db_table': 'policy',
            },
        ),
    ]
