# Generated by Django 6.0.3 on 2026-04-23 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PolicyInsurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('not_initiated', 'Not Initiated')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('issued', 'Issued'), ('payment_pending', 'Payment Pending'), ('email_flow', 'Email Flow'), ('pending', 'Pending')], max_length=30)),
                ('method', models.CharField(choices=[('api', 'API'), ('email', 'Email')], max_length=10)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quote.insurer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurers', to='Policys.policy')),
            ],
        ),
    ]
