# Generated by Django 6.0.3 on 2026-04-23 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policys', '0001_initial'),
        ('Quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyinsurer',
            name='quote_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quote.quoterequest'),
        ),
    ]
