# Generated by Django 6.0.3 on 2026-04-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policys', '0002_policyinsurer_quote_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyinsurer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('link_issued', 'Link_Issued'), ('payment_pending', 'Payment_Pending'), ('email_flow', 'Email_Flow'), ('pending_underwriter', 'Pending_underwriter')], max_length=30),
        ),
    ]
