# Generated by Django 4.2 on 2026-04-24 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policys', '0007_alter_policy_id_alter_policyinsurer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='policyinsurer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
