# Generated by Django 6.0.3 on 2026-04-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policys', '0009_alter_policy_id_alter_policyinsurer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='additional_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_additional_doc', to='Policys.policy')),
            ],
        ),
    ]
