# Generated by Django 6.0.3 on 2026-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policys', '0010_additionaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaldocument',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
