# Generated by Django 6.0.3 on 2026-04-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policys', '0012_alter_additionaldocument_id_alter_policy_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='policyinsurer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
