# Generated by Django 6.0.3 on 2026-05-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_attachment_id_alter_cooperativecustomer_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='system_generated_1',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='system_generated_2',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='system_generated_3',
        ),
    ]
